server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        path: /
        name: session

spring:
  main:
    bannerMode: "off"
  application:
    name: Guild Management Service
  error:
    include-stacktrace: never
  security:
    autoconfigure:
      exclude:
        - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
    jooq:
      sql-dialect: Postgres
    profiles:
      default:
    mvc:
      format:
        date: iso

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  show-actuator: false
  use-fqn: true

redirect:
  uri:
    allowlist:
      - https://localhost
      - https://127.0.0.1
